#!/bin/bash

# ipconfig - Version 1.0

echo
echo "IP Config - Version 1.0"
echo "======================="
echo
HOSTNAME=$(hostname)
echo "HOSTNAME: $HOSTNAME"
echo
### IP ADDRESS - WIRED ###
CARD=$(ip a | grep ": en\|: et"  |cut -d: -f2 |cut -d" " -f2)
STATUS=$(ip a | grep ": en\|: et" | grep "state UP")
if test $? = "0"; then
    IP=$(hostname -I)
    SUBNET=$(ip a | grep $IP | cut -d"/" -f2 | cut -d' ' -f1)
    echo "WIRED:"
    echo "    STATUS  : UP"
    echo "    NAME    : $CARD"
    echo "    IP      : $IP"
    echo "    SUBNET  : $SUBNET"
else
    echo "WIRED:"
    echo "    STATUS  : DOWN"
    echo "    NAME    : $CARD"
fi

### IP ADDRESS - WIRELESS ###
echo
echo "WIRELESS:"
CARD=$(ip a | grep ": wl"  |cut -d: -f2 |cut -d" " -f2)
STATUS=$(ip a | grep ": wl" | grep "state UP")
if test $? = "0"; then
    IP=$(ip a | grep -A 3  ": wl" | grep "inet " |cut -d"/" -f1 |cut -d" " -f6)
    SUBNET=$(ip a | grep -A 3 ": wl" | grep "inet " | cut -d"/" -f2 | cut -d' ' -f1)
    echo "    STATUS  : UP"
    echo "    NAME    : $CARD"
    echo "    IP      : $IP"
    echo "    SUBNET  : $SUBNET"
else
    echo "    STATUS  : DOWN"
    echo "    NAME    : $CARD"
fi

echo
echo

### DEFAULT GATEWAY ###
DEFAULT=$(ip route show | head -n 1 | cut -d" " -f3)
echo "Default   GW: $DEFAULT"

### DHCP ###
DHCP=$(ip r | head -n 1 | cut -d" " -f3)
echo "DHCP  Server: $DHCP"

### DNS ###
DNS=$(resolvectl 2>/dev/null |grep "Current DNS Server" | cut -d' ' -f4 | tr '\n' ' ')
echo "DNS   Server: $DNS"

### NETWORK CARD ###
CARD=$(ip a |grep 'state UP' | head -n 1 |cut -d: -f2 |cut -d" " -f2)
echo "Network Card: $CARD"
echo

exit 0
